# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mainWindow.ui'
#
# Created: Mon Jun 18 22:09:33 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(833, 568)
        MainWindow.setMinimumSize(QtCore.QSize(833, 568))
        MainWindow.setMaximumSize(QtCore.QSize(833, 568))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.Oscillators = QtGui.QVBoxLayout()
        self.Oscillators.setObjectName(_fromUtf8("Oscillators"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.Oscillators.addWidget(self.label_19)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.oscPWMBox = QtGui.QGroupBox(self.centralwidget)
        self.oscPWMBox.setMinimumSize(QtCore.QSize(81, 141))
        self.oscPWMBox.setMaximumSize(QtCore.QSize(81, 141))
        self.oscPWMBox.setObjectName(_fromUtf8("oscPWMBox"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.oscPWMBox)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_85 = QtGui.QVBoxLayout()
        self.verticalLayout_85.setObjectName(_fromUtf8("verticalLayout_85"))
        self.oscPWMLCD = QtGui.QLCDNumber(self.oscPWMBox)
        self.oscPWMLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.oscPWMLCD.setObjectName(_fromUtf8("oscPWMLCD"))
        self.verticalLayout_85.addWidget(self.oscPWMLCD)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem)
        self.oscPWMDial = QtGui.QDial(self.oscPWMBox)
        self.oscPWMDial.setMinimumSize(QtCore.QSize(50, 64))
        self.oscPWMDial.setMaximumSize(QtCore.QSize(50, 64))
        self.oscPWMDial.setObjectName(_fromUtf8("oscPWMDial"))
        self.horizontalLayout_26.addWidget(self.oscPWMDial)
        spacerItem1 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem1)
        self.verticalLayout_85.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_7.addLayout(self.verticalLayout_85)
        self.gridLayout_2.addWidget(self.oscPWMBox, 0, 0, 1, 1)
        self.oscDetuneBox = QtGui.QGroupBox(self.centralwidget)
        self.oscDetuneBox.setMinimumSize(QtCore.QSize(81, 141))
        self.oscDetuneBox.setMaximumSize(QtCore.QSize(81, 141))
        self.oscDetuneBox.setObjectName(_fromUtf8("oscDetuneBox"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.oscDetuneBox)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_86 = QtGui.QVBoxLayout()
        self.verticalLayout_86.setObjectName(_fromUtf8("verticalLayout_86"))
        self.oscDetuneLCD = QtGui.QLCDNumber(self.oscDetuneBox)
        self.oscDetuneLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.oscDetuneLCD.setObjectName(_fromUtf8("oscDetuneLCD"))
        self.verticalLayout_86.addWidget(self.oscDetuneLCD)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem2)
        self.oscDetuneDial = QtGui.QDial(self.oscDetuneBox)
        self.oscDetuneDial.setMinimumSize(QtCore.QSize(50, 64))
        self.oscDetuneDial.setMaximumSize(QtCore.QSize(50, 64))
        self.oscDetuneDial.setObjectName(_fromUtf8("oscDetuneDial"))
        self.horizontalLayout_27.addWidget(self.oscDetuneDial)
        spacerItem3 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem3)
        self.verticalLayout_86.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_6.addLayout(self.verticalLayout_86)
        self.gridLayout_2.addWidget(self.oscDetuneBox, 0, 1, 1, 2)
        self.oscAWaveBox = QtGui.QGroupBox(self.centralwidget)
        self.oscAWaveBox.setMinimumSize(QtCore.QSize(81, 141))
        self.oscAWaveBox.setMaximumSize(QtCore.QSize(81, 141))
        self.oscAWaveBox.setObjectName(_fromUtf8("oscAWaveBox"))
        self.verticalLayout_82 = QtGui.QVBoxLayout(self.oscAWaveBox)
        self.verticalLayout_82.setObjectName(_fromUtf8("verticalLayout_82"))
        self.verticalLayout_83 = QtGui.QVBoxLayout()
        self.verticalLayout_83.setObjectName(_fromUtf8("verticalLayout_83"))
        spacerItem4 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_83.addItem(spacerItem4)
        self.verticalLayout_84 = QtGui.QVBoxLayout()
        self.verticalLayout_84.setObjectName(_fromUtf8("verticalLayout_84"))
        self.oscAPWMOn = QtGui.QRadioButton(self.oscAWaveBox)
        self.oscAPWMOn.setObjectName(_fromUtf8("oscAPWMOn"))
        self.oscAWaveGroup = QtGui.QButtonGroup(MainWindow)
        self.oscAWaveGroup.setObjectName(_fromUtf8("oscAWaveGroup"))
        self.oscAWaveGroup.addButton(self.oscAPWMOn)
        self.verticalLayout_84.addWidget(self.oscAPWMOn)
        self.oscASawOn = QtGui.QRadioButton(self.oscAWaveBox)
        self.oscASawOn.setObjectName(_fromUtf8("oscASawOn"))
        self.oscAWaveGroup.addButton(self.oscASawOn)
        self.verticalLayout_84.addWidget(self.oscASawOn)
        self.verticalLayout_83.addLayout(self.verticalLayout_84)
        spacerItem5 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_83.addItem(spacerItem5)
        self.verticalLayout_82.addLayout(self.verticalLayout_83)
        self.gridLayout_2.addWidget(self.oscAWaveBox, 0, 3, 1, 1)
        self.oscANoiseBox = QtGui.QGroupBox(self.centralwidget)
        self.oscANoiseBox.setMinimumSize(QtCore.QSize(81, 141))
        self.oscANoiseBox.setMaximumSize(QtCore.QSize(81, 141))
        self.oscANoiseBox.setObjectName(_fromUtf8("oscANoiseBox"))
        self.verticalLayout_79 = QtGui.QVBoxLayout(self.oscANoiseBox)
        self.verticalLayout_79.setObjectName(_fromUtf8("verticalLayout_79"))
        self.verticalLayout_80 = QtGui.QVBoxLayout()
        self.verticalLayout_80.setObjectName(_fromUtf8("verticalLayout_80"))
        spacerItem6 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_80.addItem(spacerItem6)
        self.verticalLayout_81 = QtGui.QVBoxLayout()
        self.verticalLayout_81.setObjectName(_fromUtf8("verticalLayout_81"))
        self.oscANoiseOn = QtGui.QRadioButton(self.oscANoiseBox)
        self.oscANoiseOn.setObjectName(_fromUtf8("oscANoiseOn"))
        self.oscANoiseGroup = QtGui.QButtonGroup(MainWindow)
        self.oscANoiseGroup.setObjectName(_fromUtf8("oscANoiseGroup"))
        self.oscANoiseGroup.addButton(self.oscANoiseOn)
        self.verticalLayout_81.addWidget(self.oscANoiseOn)
        self.oscANoiseOff = QtGui.QRadioButton(self.oscANoiseBox)
        self.oscANoiseOff.setObjectName(_fromUtf8("oscANoiseOff"))
        self.oscANoiseGroup.addButton(self.oscANoiseOff)
        self.verticalLayout_81.addWidget(self.oscANoiseOff)
        self.verticalLayout_80.addLayout(self.verticalLayout_81)
        spacerItem7 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_80.addItem(spacerItem7)
        self.verticalLayout_79.addLayout(self.verticalLayout_80)
        self.gridLayout_2.addWidget(self.oscANoiseBox, 0, 4, 1, 1)
        self.oscBEnableBox = QtGui.QGroupBox(self.centralwidget)
        self.oscBEnableBox.setMinimumSize(QtCore.QSize(81, 141))
        self.oscBEnableBox.setMaximumSize(QtCore.QSize(81, 141))
        self.oscBEnableBox.setObjectName(_fromUtf8("oscBEnableBox"))
        self.verticalLayout_73 = QtGui.QVBoxLayout(self.oscBEnableBox)
        self.verticalLayout_73.setObjectName(_fromUtf8("verticalLayout_73"))
        self.verticalLayout_74 = QtGui.QVBoxLayout()
        self.verticalLayout_74.setObjectName(_fromUtf8("verticalLayout_74"))
        spacerItem8 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_74.addItem(spacerItem8)
        self.verticalLayout_75 = QtGui.QVBoxLayout()
        self.verticalLayout_75.setObjectName(_fromUtf8("verticalLayout_75"))
        self.oscBOn = QtGui.QRadioButton(self.oscBEnableBox)
        self.oscBOn.setObjectName(_fromUtf8("oscBOn"))
        self.oscBEnableGroup = QtGui.QButtonGroup(MainWindow)
        self.oscBEnableGroup.setObjectName(_fromUtf8("oscBEnableGroup"))
        self.oscBEnableGroup.addButton(self.oscBOn)
        self.verticalLayout_75.addWidget(self.oscBOn)
        self.oscBOff = QtGui.QRadioButton(self.oscBEnableBox)
        self.oscBOff.setObjectName(_fromUtf8("oscBOff"))
        self.oscBEnableGroup.addButton(self.oscBOff)
        self.verticalLayout_75.addWidget(self.oscBOff)
        self.verticalLayout_74.addLayout(self.verticalLayout_75)
        spacerItem9 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_74.addItem(spacerItem9)
        self.verticalLayout_73.addLayout(self.verticalLayout_74)
        self.gridLayout_2.addWidget(self.oscBEnableBox, 1, 0, 1, 2)
        self.oscBWaveBox = QtGui.QGroupBox(self.centralwidget)
        self.oscBWaveBox.setMinimumSize(QtCore.QSize(81, 141))
        self.oscBWaveBox.setMaximumSize(QtCore.QSize(81, 141))
        self.oscBWaveBox.setObjectName(_fromUtf8("oscBWaveBox"))
        self.verticalLayout_76 = QtGui.QVBoxLayout(self.oscBWaveBox)
        self.verticalLayout_76.setObjectName(_fromUtf8("verticalLayout_76"))
        self.verticalLayout_77 = QtGui.QVBoxLayout()
        self.verticalLayout_77.setObjectName(_fromUtf8("verticalLayout_77"))
        spacerItem10 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_77.addItem(spacerItem10)
        self.verticalLayout_78 = QtGui.QVBoxLayout()
        self.verticalLayout_78.setObjectName(_fromUtf8("verticalLayout_78"))
        self.oscBWaveSquare = QtGui.QRadioButton(self.oscBWaveBox)
        self.oscBWaveSquare.setObjectName(_fromUtf8("oscBWaveSquare"))
        self.oscBWaveGroup = QtGui.QButtonGroup(MainWindow)
        self.oscBWaveGroup.setObjectName(_fromUtf8("oscBWaveGroup"))
        self.oscBWaveGroup.addButton(self.oscBWaveSquare)
        self.verticalLayout_78.addWidget(self.oscBWaveSquare)
        self.oscBWaveTri = QtGui.QRadioButton(self.oscBWaveBox)
        self.oscBWaveTri.setObjectName(_fromUtf8("oscBWaveTri"))
        self.oscBWaveGroup.addButton(self.oscBWaveTri)
        self.verticalLayout_78.addWidget(self.oscBWaveTri)
        self.verticalLayout_77.addLayout(self.verticalLayout_78)
        spacerItem11 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_77.addItem(spacerItem11)
        self.verticalLayout_76.addLayout(self.verticalLayout_77)
        self.gridLayout_2.addWidget(self.oscBWaveBox, 1, 2, 1, 1)
        self.oscBOctaveBox = QtGui.QGroupBox(self.centralwidget)
        self.oscBOctaveBox.setMinimumSize(QtCore.QSize(81, 141))
        self.oscBOctaveBox.setMaximumSize(QtCore.QSize(81, 141))
        self.oscBOctaveBox.setObjectName(_fromUtf8("oscBOctaveBox"))
        self.verticalLayout_70 = QtGui.QVBoxLayout(self.oscBOctaveBox)
        self.verticalLayout_70.setObjectName(_fromUtf8("verticalLayout_70"))
        self.verticalLayout_71 = QtGui.QVBoxLayout()
        self.verticalLayout_71.setObjectName(_fromUtf8("verticalLayout_71"))
        spacerItem12 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_71.addItem(spacerItem12)
        self.verticalLayout_72 = QtGui.QVBoxLayout()
        self.verticalLayout_72.setObjectName(_fromUtf8("verticalLayout_72"))
        self.oscBOctaveOn = QtGui.QRadioButton(self.oscBOctaveBox)
        self.oscBOctaveOn.setObjectName(_fromUtf8("oscBOctaveOn"))
        self.oscBOctaveGroup = QtGui.QButtonGroup(MainWindow)
        self.oscBOctaveGroup.setObjectName(_fromUtf8("oscBOctaveGroup"))
        self.oscBOctaveGroup.addButton(self.oscBOctaveOn)
        self.verticalLayout_72.addWidget(self.oscBOctaveOn)
        self.oscBOctaveOff = QtGui.QRadioButton(self.oscBOctaveBox)
        self.oscBOctaveOff.setObjectName(_fromUtf8("oscBOctaveOff"))
        self.oscBOctaveGroup.addButton(self.oscBOctaveOff)
        self.verticalLayout_72.addWidget(self.oscBOctaveOff)
        self.verticalLayout_71.addLayout(self.verticalLayout_72)
        spacerItem13 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_71.addItem(spacerItem13)
        self.verticalLayout_70.addLayout(self.verticalLayout_71)
        self.gridLayout_2.addWidget(self.oscBOctaveBox, 1, 3, 1, 1)
        self.oscFMBox = QtGui.QGroupBox(self.centralwidget)
        self.oscFMBox.setMinimumSize(QtCore.QSize(81, 141))
        self.oscFMBox.setMaximumSize(QtCore.QSize(81, 141))
        self.oscFMBox.setObjectName(_fromUtf8("oscFMBox"))
        self.verticalLayout_67 = QtGui.QVBoxLayout(self.oscFMBox)
        self.verticalLayout_67.setObjectName(_fromUtf8("verticalLayout_67"))
        self.verticalLayout_68 = QtGui.QVBoxLayout()
        self.verticalLayout_68.setObjectName(_fromUtf8("verticalLayout_68"))
        spacerItem14 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_68.addItem(spacerItem14)
        self.verticalLayout_69 = QtGui.QVBoxLayout()
        self.verticalLayout_69.setObjectName(_fromUtf8("verticalLayout_69"))
        self.oscFMOn = QtGui.QRadioButton(self.oscFMBox)
        self.oscFMOn.setObjectName(_fromUtf8("oscFMOn"))
        self.oscFMGroup = QtGui.QButtonGroup(MainWindow)
        self.oscFMGroup.setObjectName(_fromUtf8("oscFMGroup"))
        self.oscFMGroup.addButton(self.oscFMOn)
        self.verticalLayout_69.addWidget(self.oscFMOn)
        self.oscFMOff = QtGui.QRadioButton(self.oscFMBox)
        self.oscFMOff.setObjectName(_fromUtf8("oscFMOff"))
        self.oscFMGroup.addButton(self.oscFMOff)
        self.verticalLayout_69.addWidget(self.oscFMOff)
        self.verticalLayout_68.addLayout(self.verticalLayout_69)
        spacerItem15 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_68.addItem(spacerItem15)
        self.verticalLayout_67.addLayout(self.verticalLayout_68)
        self.gridLayout_2.addWidget(self.oscFMBox, 1, 4, 1, 1)
        self.Oscillators.addLayout(self.gridLayout_2)
        self.horizontalLayout_15.addLayout(self.Oscillators)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_15.addWidget(self.line_2)
        self.Filter = QtGui.QVBoxLayout()
        self.Filter.setObjectName(_fromUtf8("Filter"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.Filter.addWidget(self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.filterAttackBox = QtGui.QGroupBox(self.centralwidget)
        self.filterAttackBox.setMinimumSize(QtCore.QSize(81, 141))
        self.filterAttackBox.setMaximumSize(QtCore.QSize(81, 141))
        self.filterAttackBox.setObjectName(_fromUtf8("filterAttackBox"))
        self.layoutWidget_8 = QtGui.QWidget(self.filterAttackBox)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 20, 66, 117))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_31.setMargin(0)
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.filterAttackLCD = QtGui.QLCDNumber(self.layoutWidget_8)
        self.filterAttackLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.filterAttackLCD.setObjectName(_fromUtf8("filterAttackLCD"))
        self.verticalLayout_31.addWidget(self.filterAttackLCD)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem16 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        self.filterAttackSlider = QtGui.QSlider(self.layoutWidget_8)
        self.filterAttackSlider.setOrientation(QtCore.Qt.Vertical)
        self.filterAttackSlider.setObjectName(_fromUtf8("filterAttackSlider"))
        self.horizontalLayout_16.addWidget(self.filterAttackSlider)
        spacerItem17 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem17)
        self.verticalLayout_31.addLayout(self.horizontalLayout_16)
        self.gridLayout.addWidget(self.filterAttackBox, 0, 0, 1, 1)
        self.filterDecayBox = QtGui.QGroupBox(self.centralwidget)
        self.filterDecayBox.setMinimumSize(QtCore.QSize(81, 141))
        self.filterDecayBox.setMaximumSize(QtCore.QSize(81, 141))
        self.filterDecayBox.setObjectName(_fromUtf8("filterDecayBox"))
        self.layoutWidget_9 = QtGui.QWidget(self.filterDecayBox)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 20, 66, 117))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_32.setMargin(0)
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.filterDecayLCD = QtGui.QLCDNumber(self.layoutWidget_9)
        self.filterDecayLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.filterDecayLCD.setObjectName(_fromUtf8("filterDecayLCD"))
        self.verticalLayout_32.addWidget(self.filterDecayLCD)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem18 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem18)
        self.filterDecaySlider = QtGui.QSlider(self.layoutWidget_9)
        self.filterDecaySlider.setOrientation(QtCore.Qt.Vertical)
        self.filterDecaySlider.setObjectName(_fromUtf8("filterDecaySlider"))
        self.horizontalLayout_17.addWidget(self.filterDecaySlider)
        spacerItem19 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem19)
        self.verticalLayout_32.addLayout(self.horizontalLayout_17)
        self.gridLayout.addWidget(self.filterDecayBox, 0, 1, 1, 1)
        self.filterModeBox = QtGui.QGroupBox(self.centralwidget)
        self.filterModeBox.setMinimumSize(QtCore.QSize(81, 141))
        self.filterModeBox.setMaximumSize(QtCore.QSize(81, 141))
        self.filterModeBox.setObjectName(_fromUtf8("filterModeBox"))
        self.verticalLayout_64 = QtGui.QVBoxLayout(self.filterModeBox)
        self.verticalLayout_64.setObjectName(_fromUtf8("verticalLayout_64"))
        self.verticalLayout_65 = QtGui.QVBoxLayout()
        self.verticalLayout_65.setObjectName(_fromUtf8("verticalLayout_65"))
        spacerItem20 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_65.addItem(spacerItem20)
        self.verticalLayout_66 = QtGui.QVBoxLayout()
        self.verticalLayout_66.setObjectName(_fromUtf8("verticalLayout_66"))
        self.hpOn = QtGui.QRadioButton(self.filterModeBox)
        self.hpOn.setObjectName(_fromUtf8("hpOn"))
        self.filterModeGroup = QtGui.QButtonGroup(MainWindow)
        self.filterModeGroup.setObjectName(_fromUtf8("filterModeGroup"))
        self.filterModeGroup.addButton(self.hpOn)
        self.verticalLayout_66.addWidget(self.hpOn)
        self.lpOn = QtGui.QRadioButton(self.filterModeBox)
        self.lpOn.setObjectName(_fromUtf8("lpOn"))
        self.filterModeGroup.addButton(self.lpOn)
        self.verticalLayout_66.addWidget(self.lpOn)
        self.verticalLayout_65.addLayout(self.verticalLayout_66)
        spacerItem21 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_65.addItem(spacerItem21)
        self.verticalLayout_64.addLayout(self.verticalLayout_65)
        self.gridLayout.addWidget(self.filterModeBox, 0, 2, 1, 1)
        self.cutoffBox = QtGui.QGroupBox(self.centralwidget)
        self.cutoffBox.setMinimumSize(QtCore.QSize(81, 141))
        self.cutoffBox.setMaximumSize(QtCore.QSize(81, 141))
        self.cutoffBox.setObjectName(_fromUtf8("cutoffBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.cutoffBox)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_63 = QtGui.QVBoxLayout()
        self.verticalLayout_63.setObjectName(_fromUtf8("verticalLayout_63"))
        self.cutoffLCD = QtGui.QLCDNumber(self.cutoffBox)
        self.cutoffLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.cutoffLCD.setObjectName(_fromUtf8("cutoffLCD"))
        self.verticalLayout_63.addWidget(self.cutoffLCD)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        spacerItem22 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem22)
        self.cutoffDial = QtGui.QDial(self.cutoffBox)
        self.cutoffDial.setMinimumSize(QtCore.QSize(50, 64))
        self.cutoffDial.setMaximumSize(QtCore.QSize(50, 64))
        self.cutoffDial.setObjectName(_fromUtf8("cutoffDial"))
        self.horizontalLayout_25.addWidget(self.cutoffDial)
        spacerItem23 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem23)
        self.verticalLayout_63.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_5.addLayout(self.verticalLayout_63)
        self.gridLayout.addWidget(self.cutoffBox, 1, 0, 1, 1)
        self.resonanceBox = QtGui.QGroupBox(self.centralwidget)
        self.resonanceBox.setMinimumSize(QtCore.QSize(81, 141))
        self.resonanceBox.setMaximumSize(QtCore.QSize(81, 141))
        self.resonanceBox.setObjectName(_fromUtf8("resonanceBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.resonanceBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_62 = QtGui.QVBoxLayout()
        self.verticalLayout_62.setObjectName(_fromUtf8("verticalLayout_62"))
        self.resonanceLCD = QtGui.QLCDNumber(self.resonanceBox)
        self.resonanceLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.resonanceLCD.setObjectName(_fromUtf8("resonanceLCD"))
        self.verticalLayout_62.addWidget(self.resonanceLCD)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        spacerItem24 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem24)
        self.resonanceDial = QtGui.QDial(self.resonanceBox)
        self.resonanceDial.setMinimumSize(QtCore.QSize(50, 64))
        self.resonanceDial.setMaximumSize(QtCore.QSize(50, 64))
        self.resonanceDial.setObjectName(_fromUtf8("resonanceDial"))
        self.horizontalLayout_24.addWidget(self.resonanceDial)
        spacerItem25 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem25)
        self.verticalLayout_62.addLayout(self.horizontalLayout_24)
        self.horizontalLayout.addLayout(self.verticalLayout_62)
        self.gridLayout.addWidget(self.resonanceBox, 1, 1, 1, 1)
        self.envAmountBox = QtGui.QGroupBox(self.centralwidget)
        self.envAmountBox.setMinimumSize(QtCore.QSize(81, 141))
        self.envAmountBox.setMaximumSize(QtCore.QSize(81, 141))
        self.envAmountBox.setObjectName(_fromUtf8("envAmountBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.envAmountBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_61 = QtGui.QVBoxLayout()
        self.verticalLayout_61.setObjectName(_fromUtf8("verticalLayout_61"))
        self.envAmountLCD = QtGui.QLCDNumber(self.envAmountBox)
        self.envAmountLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.envAmountLCD.setObjectName(_fromUtf8("envAmountLCD"))
        self.verticalLayout_61.addWidget(self.envAmountLCD)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem26 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem26)
        self.envAmountDial = QtGui.QDial(self.envAmountBox)
        self.envAmountDial.setMinimumSize(QtCore.QSize(50, 64))
        self.envAmountDial.setMaximumSize(QtCore.QSize(50, 64))
        self.envAmountDial.setObjectName(_fromUtf8("envAmountDial"))
        self.horizontalLayout_22.addWidget(self.envAmountDial)
        spacerItem27 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem27)
        self.verticalLayout_61.addLayout(self.horizontalLayout_22)
        self.verticalLayout.addLayout(self.verticalLayout_61)
        self.gridLayout.addWidget(self.envAmountBox, 1, 2, 1, 1)
        self.Filter.addLayout(self.gridLayout)
        self.horizontalLayout_15.addLayout(self.Filter)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_15.addWidget(self.line_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ampAttackBox = QtGui.QGroupBox(self.centralwidget)
        self.ampAttackBox.setMinimumSize(QtCore.QSize(81, 141))
        self.ampAttackBox.setMaximumSize(QtCore.QSize(81, 141))
        self.ampAttackBox.setObjectName(_fromUtf8("ampAttackBox"))
        self.layoutWidget_4 = QtGui.QWidget(self.ampAttackBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 66, 117))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.ampAttackLCD = QtGui.QLCDNumber(self.layoutWidget_4)
        self.ampAttackLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.ampAttackLCD.setObjectName(_fromUtf8("ampAttackLCD"))
        self.verticalLayout_16.addWidget(self.ampAttackLCD)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem28 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem28)
        self.ampAttackSlider = QtGui.QSlider(self.layoutWidget_4)
        self.ampAttackSlider.setOrientation(QtCore.Qt.Vertical)
        self.ampAttackSlider.setObjectName(_fromUtf8("ampAttackSlider"))
        self.horizontalLayout_10.addWidget(self.ampAttackSlider)
        spacerItem29 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem29)
        self.verticalLayout_16.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8.addWidget(self.ampAttackBox)
        self.ampDecayBox = QtGui.QGroupBox(self.centralwidget)
        self.ampDecayBox.setMinimumSize(QtCore.QSize(81, 141))
        self.ampDecayBox.setMaximumSize(QtCore.QSize(81, 141))
        self.ampDecayBox.setObjectName(_fromUtf8("ampDecayBox"))
        self.layoutWidget = QtGui.QWidget(self.ampDecayBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 66, 117))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.ampDecayLCD = QtGui.QLCDNumber(self.layoutWidget)
        self.ampDecayLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.ampDecayLCD.setObjectName(_fromUtf8("ampDecayLCD"))
        self.verticalLayout_15.addWidget(self.ampDecayLCD)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem30 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem30)
        self.ampDecaySlider = QtGui.QSlider(self.layoutWidget)
        self.ampDecaySlider.setOrientation(QtCore.Qt.Vertical)
        self.ampDecaySlider.setObjectName(_fromUtf8("ampDecaySlider"))
        self.horizontalLayout_9.addWidget(self.ampDecaySlider)
        spacerItem31 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem31)
        self.verticalLayout_15.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addWidget(self.ampDecayBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.envSustainBox = QtGui.QGroupBox(self.centralwidget)
        self.envSustainBox.setMaximumSize(QtCore.QSize(81, 141))
        self.envSustainBox.setObjectName(_fromUtf8("envSustainBox"))
        self.verticalLayout_89 = QtGui.QVBoxLayout(self.envSustainBox)
        self.verticalLayout_89.setObjectName(_fromUtf8("verticalLayout_89"))
        self.verticalLayout_90 = QtGui.QVBoxLayout()
        self.verticalLayout_90.setObjectName(_fromUtf8("verticalLayout_90"))
        spacerItem32 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_90.addItem(spacerItem32)
        self.verticalLayout_91 = QtGui.QVBoxLayout()
        self.verticalLayout_91.setObjectName(_fromUtf8("verticalLayout_91"))
        self.envSustainOn = QtGui.QRadioButton(self.envSustainBox)
        self.envSustainOn.setObjectName(_fromUtf8("envSustainOn"))
        self.envSustainGroup = QtGui.QButtonGroup(MainWindow)
        self.envSustainGroup.setObjectName(_fromUtf8("envSustainGroup"))
        self.envSustainGroup.addButton(self.envSustainOn)
        self.verticalLayout_91.addWidget(self.envSustainOn)
        self.envSustainOff = QtGui.QRadioButton(self.envSustainBox)
        self.envSustainOff.setObjectName(_fromUtf8("envSustainOff"))
        self.envSustainGroup.addButton(self.envSustainOff)
        self.verticalLayout_91.addWidget(self.envSustainOff)
        self.verticalLayout_90.addLayout(self.verticalLayout_91)
        spacerItem33 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_90.addItem(spacerItem33)
        self.verticalLayout_89.addLayout(self.verticalLayout_90)
        self.horizontalLayout_14.addWidget(self.envSustainBox)
        self.glideBox = QtGui.QGroupBox(self.centralwidget)
        self.glideBox.setMinimumSize(QtCore.QSize(81, 141))
        self.glideBox.setMaximumSize(QtCore.QSize(81, 141))
        self.glideBox.setObjectName(_fromUtf8("glideBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.glideBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_40 = QtGui.QVBoxLayout()
        self.verticalLayout_40.setObjectName(_fromUtf8("verticalLayout_40"))
        self.glideAmountLCD = QtGui.QLCDNumber(self.glideBox)
        self.glideAmountLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.glideAmountLCD.setObjectName(_fromUtf8("glideAmountLCD"))
        self.verticalLayout_40.addWidget(self.glideAmountLCD)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem34 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem34)
        self.glideAmountDial = QtGui.QDial(self.glideBox)
        self.glideAmountDial.setMinimumSize(QtCore.QSize(50, 64))
        self.glideAmountDial.setMaximumSize(QtCore.QSize(50, 64))
        self.glideAmountDial.setObjectName(_fromUtf8("glideAmountDial"))
        self.horizontalLayout_19.addWidget(self.glideAmountDial)
        spacerItem35 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem35)
        self.verticalLayout_40.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_2.addLayout(self.verticalLayout_40)
        self.horizontalLayout_14.addWidget(self.glideBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.LFO = QtGui.QVBoxLayout()
        self.LFO.setObjectName(_fromUtf8("LFO"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.LFO.addWidget(self.label_22)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.LFORateBox = QtGui.QGroupBox(self.centralwidget)
        self.LFORateBox.setMinimumSize(QtCore.QSize(81, 141))
        self.LFORateBox.setMaximumSize(QtCore.QSize(81, 141))
        self.LFORateBox.setObjectName(_fromUtf8("LFORateBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.LFORateBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_59 = QtGui.QVBoxLayout()
        self.verticalLayout_59.setObjectName(_fromUtf8("verticalLayout_59"))
        self.lfoRateLCD = QtGui.QLCDNumber(self.LFORateBox)
        self.lfoRateLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.lfoRateLCD.setObjectName(_fromUtf8("lfoRateLCD"))
        self.verticalLayout_59.addWidget(self.lfoRateLCD)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem36 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem36)
        self.lfoRateDial = QtGui.QDial(self.LFORateBox)
        self.lfoRateDial.setMinimumSize(QtCore.QSize(50, 64))
        self.lfoRateDial.setMaximumSize(QtCore.QSize(50, 64))
        self.lfoRateDial.setObjectName(_fromUtf8("lfoRateDial"))
        self.horizontalLayout_21.addWidget(self.lfoRateDial)
        spacerItem37 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem37)
        self.verticalLayout_59.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_4.addLayout(self.verticalLayout_59)
        self.horizontalLayout_11.addWidget(self.LFORateBox)
        self.LFODepthBox = QtGui.QGroupBox(self.centralwidget)
        self.LFODepthBox.setMinimumSize(QtCore.QSize(81, 141))
        self.LFODepthBox.setMaximumSize(QtCore.QSize(81, 141))
        self.LFODepthBox.setObjectName(_fromUtf8("LFODepthBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.LFODepthBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_60 = QtGui.QVBoxLayout()
        self.verticalLayout_60.setObjectName(_fromUtf8("verticalLayout_60"))
        self.lfoDepthLCD = QtGui.QLCDNumber(self.LFODepthBox)
        self.lfoDepthLCD.setMaximumSize(QtCore.QSize(64, 23))
        self.lfoDepthLCD.setObjectName(_fromUtf8("lfoDepthLCD"))
        self.verticalLayout_60.addWidget(self.lfoDepthLCD)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        spacerItem38 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem38)
        self.lfoDepthDial = QtGui.QDial(self.LFODepthBox)
        self.lfoDepthDial.setMinimumSize(QtCore.QSize(50, 64))
        self.lfoDepthDial.setMaximumSize(QtCore.QSize(50, 64))
        self.lfoDepthDial.setObjectName(_fromUtf8("lfoDepthDial"))
        self.horizontalLayout_23.addWidget(self.lfoDepthDial)
        spacerItem39 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem39)
        self.verticalLayout_60.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_3.addLayout(self.verticalLayout_60)
        self.horizontalLayout_11.addWidget(self.LFODepthBox)
        self.lfoEnableBox = QtGui.QGroupBox(self.centralwidget)
        self.lfoEnableBox.setMinimumSize(QtCore.QSize(81, 141))
        self.lfoEnableBox.setMaximumSize(QtCore.QSize(81, 141))
        self.lfoEnableBox.setObjectName(_fromUtf8("lfoEnableBox"))
        self.verticalLayout_56 = QtGui.QVBoxLayout(self.lfoEnableBox)
        self.verticalLayout_56.setObjectName(_fromUtf8("verticalLayout_56"))
        self.verticalLayout_57 = QtGui.QVBoxLayout()
        self.verticalLayout_57.setObjectName(_fromUtf8("verticalLayout_57"))
        spacerItem40 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_57.addItem(spacerItem40)
        self.verticalLayout_58 = QtGui.QVBoxLayout()
        self.verticalLayout_58.setObjectName(_fromUtf8("verticalLayout_58"))
        self.lfoOn = QtGui.QRadioButton(self.lfoEnableBox)
        self.lfoOn.setObjectName(_fromUtf8("lfoOn"))
        self.lfoEnableGroup = QtGui.QButtonGroup(MainWindow)
        self.lfoEnableGroup.setObjectName(_fromUtf8("lfoEnableGroup"))
        self.lfoEnableGroup.addButton(self.lfoOn)
        self.verticalLayout_58.addWidget(self.lfoOn)
        self.lfoOff = QtGui.QRadioButton(self.lfoEnableBox)
        self.lfoOff.setObjectName(_fromUtf8("lfoOff"))
        self.lfoEnableGroup.addButton(self.lfoOff)
        self.verticalLayout_58.addWidget(self.lfoOff)
        self.verticalLayout_57.addLayout(self.verticalLayout_58)
        spacerItem41 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_57.addItem(spacerItem41)
        self.verticalLayout_56.addLayout(self.verticalLayout_57)
        self.horizontalLayout_11.addWidget(self.lfoEnableBox)
        self.lfoDestBox = QtGui.QGroupBox(self.centralwidget)
        self.lfoDestBox.setMinimumSize(QtCore.QSize(81, 141))
        self.lfoDestBox.setMaximumSize(QtCore.QSize(81, 141))
        self.lfoDestBox.setObjectName(_fromUtf8("lfoDestBox"))
        self.verticalLayout_53 = QtGui.QVBoxLayout(self.lfoDestBox)
        self.verticalLayout_53.setObjectName(_fromUtf8("verticalLayout_53"))
        self.verticalLayout_54 = QtGui.QVBoxLayout()
        self.verticalLayout_54.setObjectName(_fromUtf8("verticalLayout_54"))
        spacerItem42 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_54.addItem(spacerItem42)
        self.verticalLayout_55 = QtGui.QVBoxLayout()
        self.verticalLayout_55.setObjectName(_fromUtf8("verticalLayout_55"))
        self.lfoOscOn = QtGui.QRadioButton(self.lfoDestBox)
        self.lfoOscOn.setObjectName(_fromUtf8("lfoOscOn"))
        self.lfoDestGroup = QtGui.QButtonGroup(MainWindow)
        self.lfoDestGroup.setObjectName(_fromUtf8("lfoDestGroup"))
        self.lfoDestGroup.addButton(self.lfoOscOn)
        self.verticalLayout_55.addWidget(self.lfoOscOn)
        self.lfoFilterOn = QtGui.QRadioButton(self.lfoDestBox)
        self.lfoFilterOn.setObjectName(_fromUtf8("lfoFilterOn"))
        self.lfoDestGroup.addButton(self.lfoFilterOn)
        self.verticalLayout_55.addWidget(self.lfoFilterOn)
        self.verticalLayout_54.addLayout(self.verticalLayout_55)
        spacerItem43 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_54.addItem(spacerItem43)
        self.verticalLayout_53.addLayout(self.verticalLayout_54)
        self.horizontalLayout_11.addWidget(self.lfoDestBox)
        self.lfoWaveBox = QtGui.QGroupBox(self.centralwidget)
        self.lfoWaveBox.setMinimumSize(QtCore.QSize(81, 141))
        self.lfoWaveBox.setMaximumSize(QtCore.QSize(81, 141))
        self.lfoWaveBox.setObjectName(_fromUtf8("lfoWaveBox"))
        self.verticalLayout_50 = QtGui.QVBoxLayout(self.lfoWaveBox)
        self.verticalLayout_50.setObjectName(_fromUtf8("verticalLayout_50"))
        self.verticalLayout_51 = QtGui.QVBoxLayout()
        self.verticalLayout_51.setObjectName(_fromUtf8("verticalLayout_51"))
        spacerItem44 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_51.addItem(spacerItem44)
        self.verticalLayout_52 = QtGui.QVBoxLayout()
        self.verticalLayout_52.setObjectName(_fromUtf8("verticalLayout_52"))
        self.lfoSquareOn = QtGui.QRadioButton(self.lfoWaveBox)
        self.lfoSquareOn.setObjectName(_fromUtf8("lfoSquareOn"))
        self.lfoWaveGroup = QtGui.QButtonGroup(MainWindow)
        self.lfoWaveGroup.setObjectName(_fromUtf8("lfoWaveGroup"))
        self.lfoWaveGroup.addButton(self.lfoSquareOn)
        self.verticalLayout_52.addWidget(self.lfoSquareOn)
        self.lfoTriangleOn = QtGui.QRadioButton(self.lfoWaveBox)
        self.lfoTriangleOn.setObjectName(_fromUtf8("lfoTriangleOn"))
        self.lfoWaveGroup.addButton(self.lfoTriangleOn)
        self.verticalLayout_52.addWidget(self.lfoTriangleOn)
        self.verticalLayout_51.addLayout(self.verticalLayout_52)
        spacerItem45 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_51.addItem(spacerItem45)
        self.verticalLayout_50.addLayout(self.verticalLayout_51)
        self.horizontalLayout_11.addWidget(self.lfoWaveBox)
        self.lfoRandomBox = QtGui.QGroupBox(self.centralwidget)
        self.lfoRandomBox.setMinimumSize(QtCore.QSize(81, 141))
        self.lfoRandomBox.setMaximumSize(QtCore.QSize(81, 141))
        self.lfoRandomBox.setObjectName(_fromUtf8("lfoRandomBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.lfoRandomBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_48 = QtGui.QVBoxLayout()
        self.verticalLayout_48.setObjectName(_fromUtf8("verticalLayout_48"))
        spacerItem46 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_48.addItem(spacerItem46)
        self.verticalLayout_49 = QtGui.QVBoxLayout()
        self.verticalLayout_49.setObjectName(_fromUtf8("verticalLayout_49"))
        self.lfoRandomOn = QtGui.QRadioButton(self.lfoRandomBox)
        self.lfoRandomOn.setObjectName(_fromUtf8("lfoRandomOn"))
        self.lfoRandomGroup = QtGui.QButtonGroup(MainWindow)
        self.lfoRandomGroup.setObjectName(_fromUtf8("lfoRandomGroup"))
        self.lfoRandomGroup.addButton(self.lfoRandomOn)
        self.verticalLayout_49.addWidget(self.lfoRandomOn)
        self.lfoRandomOff = QtGui.QRadioButton(self.lfoRandomBox)
        self.lfoRandomOff.setObjectName(_fromUtf8("lfoRandomOff"))
        self.lfoRandomGroup.addButton(self.lfoRandomOff)
        self.verticalLayout_49.addWidget(self.lfoRandomOff)
        self.verticalLayout_48.addLayout(self.verticalLayout_49)
        spacerItem47 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_48.addItem(spacerItem47)
        self.verticalLayout_2.addLayout(self.verticalLayout_48)
        self.horizontalLayout_11.addWidget(self.lfoRandomBox)
        self.LFO.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13.addLayout(self.LFO)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_13.addWidget(self.line_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_3.addWidget(self.label_28)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.pwmSweepBox = QtGui.QGroupBox(self.centralwidget)
        self.pwmSweepBox.setMaximumSize(QtCore.QSize(81, 141))
        self.pwmSweepBox.setObjectName(_fromUtf8("pwmSweepBox"))
        self.verticalLayout_92 = QtGui.QVBoxLayout(self.pwmSweepBox)
        self.verticalLayout_92.setObjectName(_fromUtf8("verticalLayout_92"))
        self.verticalLayout_93 = QtGui.QVBoxLayout()
        self.verticalLayout_93.setObjectName(_fromUtf8("verticalLayout_93"))
        spacerItem48 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_93.addItem(spacerItem48)
        self.verticalLayout_94 = QtGui.QVBoxLayout()
        self.verticalLayout_94.setObjectName(_fromUtf8("verticalLayout_94"))
        self.pwmSweepOn = QtGui.QRadioButton(self.pwmSweepBox)
        self.pwmSweepOn.setObjectName(_fromUtf8("pwmSweepOn"))
        self.pwmSweepGroup = QtGui.QButtonGroup(MainWindow)
        self.pwmSweepGroup.setObjectName(_fromUtf8("pwmSweepGroup"))
        self.pwmSweepGroup.addButton(self.pwmSweepOn)
        self.verticalLayout_94.addWidget(self.pwmSweepOn)
        self.pwmSweepOff = QtGui.QRadioButton(self.pwmSweepBox)
        self.pwmSweepOff.setObjectName(_fromUtf8("pwmSweepOff"))
        self.pwmSweepGroup.addButton(self.pwmSweepOff)
        self.verticalLayout_94.addWidget(self.pwmSweepOff)
        self.verticalLayout_93.addLayout(self.verticalLayout_94)
        spacerItem49 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_93.addItem(spacerItem49)
        self.verticalLayout_92.addLayout(self.verticalLayout_93)
        self.horizontalLayout_12.addWidget(self.pwmSweepBox)
        self.distortionBox = QtGui.QGroupBox(self.centralwidget)
        self.distortionBox.setMaximumSize(QtCore.QSize(81, 141))
        self.distortionBox.setObjectName(_fromUtf8("distortionBox"))
        self.verticalLayout_46 = QtGui.QVBoxLayout(self.distortionBox)
        self.verticalLayout_46.setObjectName(_fromUtf8("verticalLayout_46"))
        self.verticalLayout_43 = QtGui.QVBoxLayout()
        self.verticalLayout_43.setObjectName(_fromUtf8("verticalLayout_43"))
        spacerItem50 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_43.addItem(spacerItem50)
        self.verticalLayout_44 = QtGui.QVBoxLayout()
        self.verticalLayout_44.setObjectName(_fromUtf8("verticalLayout_44"))
        self.distortionOn = QtGui.QRadioButton(self.distortionBox)
        self.distortionOn.setObjectName(_fromUtf8("distortionOn"))
        self.distortionGroup = QtGui.QButtonGroup(MainWindow)
        self.distortionGroup.setObjectName(_fromUtf8("distortionGroup"))
        self.distortionGroup.addButton(self.distortionOn)
        self.verticalLayout_44.addWidget(self.distortionOn)
        self.distortionOff = QtGui.QRadioButton(self.distortionBox)
        self.distortionOff.setObjectName(_fromUtf8("distortionOff"))
        self.distortionGroup.addButton(self.distortionOff)
        self.verticalLayout_44.addWidget(self.distortionOff)
        self.verticalLayout_43.addLayout(self.verticalLayout_44)
        spacerItem51 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_43.addItem(spacerItem51)
        self.verticalLayout_46.addLayout(self.verticalLayout_43)
        self.horizontalLayout_12.addWidget(self.distortionBox)
        self.antiAliasBox = QtGui.QGroupBox(self.centralwidget)
        self.antiAliasBox.setMinimumSize(QtCore.QSize(81, 141))
        self.antiAliasBox.setMaximumSize(QtCore.QSize(81, 141))
        self.antiAliasBox.setObjectName(_fromUtf8("antiAliasBox"))
        self.verticalLayout_45 = QtGui.QVBoxLayout(self.antiAliasBox)
        self.verticalLayout_45.setObjectName(_fromUtf8("verticalLayout_45"))
        self.verticalLayout_41 = QtGui.QVBoxLayout()
        self.verticalLayout_41.setObjectName(_fromUtf8("verticalLayout_41"))
        spacerItem52 = QtGui.QSpacerItem(66, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_41.addItem(spacerItem52)
        self.verticalLayout_42 = QtGui.QVBoxLayout()
        self.verticalLayout_42.setObjectName(_fromUtf8("verticalLayout_42"))
        self.antiAliasOn = QtGui.QRadioButton(self.antiAliasBox)
        self.antiAliasOn.setObjectName(_fromUtf8("antiAliasOn"))
        self.antiAliasGroup = QtGui.QButtonGroup(MainWindow)
        self.antiAliasGroup.setObjectName(_fromUtf8("antiAliasGroup"))
        self.antiAliasGroup.addButton(self.antiAliasOn)
        self.verticalLayout_42.addWidget(self.antiAliasOn)
        self.antiAliasOff = QtGui.QRadioButton(self.antiAliasBox)
        self.antiAliasOff.setObjectName(_fromUtf8("antiAliasOff"))
        self.antiAliasGroup.addButton(self.antiAliasOff)
        self.verticalLayout_42.addWidget(self.antiAliasOff)
        self.verticalLayout_41.addLayout(self.verticalLayout_42)
        spacerItem53 = QtGui.QSpacerItem(71, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_41.addItem(spacerItem53)
        self.verticalLayout_45.addLayout(self.verticalLayout_41)
        self.horizontalLayout_12.addWidget(self.antiAliasBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13.addLayout(self.verticalLayout_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        MainWindow.setMenuBar(self.menubar)
        self.action_Load = QtGui.QAction(MainWindow)
        self.action_Load.setObjectName(_fromUtf8("action_Load"))
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_Save_as = QtGui.QAction(MainWindow)
        self.action_Save_as.setObjectName(_fromUtf8("action_Save_as"))
        self.action_MIDI_Channel = QtGui.QAction(MainWindow)
        self.action_MIDI_Channel.setObjectName(_fromUtf8("action_MIDI_Channel"))
        self.action_Export_patch_as_MIDI = QtGui.QAction(MainWindow)
        self.action_Export_patch_as_MIDI.setObjectName(_fromUtf8("action_Export_patch_as_MIDI"))
        self.action_Import_MIDI_patch = QtGui.QAction(MainWindow)
        self.action_Import_MIDI_patch.setObjectName(_fromUtf8("action_Import_MIDI_patch"))
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_New = QtGui.QAction(MainWindow)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Load)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Save_as)
        self.menuFile.addAction(self.action_Export_patch_as_MIDI)
        self.menuFile.addAction(self.action_Import_MIDI_patch)
        self.menuFile.addAction(self.action_Exit)
        self.menuOptions.addAction(self.action_MIDI_Channel)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.oscPWMDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.oscPWMLCD.display)
        QtCore.QObject.connect(self.oscDetuneDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.oscDetuneLCD.display)
        QtCore.QObject.connect(self.lfoRateDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lfoRateLCD.display)
        QtCore.QObject.connect(self.lfoDepthDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lfoDepthLCD.display)
        QtCore.QObject.connect(self.filterAttackSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.filterAttackLCD.display)
        QtCore.QObject.connect(self.filterDecaySlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.filterDecayLCD.display)
        QtCore.QObject.connect(self.cutoffDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.cutoffLCD.display)
        QtCore.QObject.connect(self.resonanceDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.resonanceLCD.display)
        QtCore.QObject.connect(self.envAmountDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.envAmountLCD.display)
        QtCore.QObject.connect(self.ampAttackSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.ampAttackLCD.display)
        QtCore.QObject.connect(self.ampDecaySlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.ampDecayLCD.display)
        QtCore.QObject.connect(self.glideAmountDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.glideAmountLCD.display)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Oscillators</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.oscPWMBox.setTitle(QtGui.QApplication.translate("MainWindow", "Osc. PWM", None, QtGui.QApplication.UnicodeUTF8))
        self.oscDetuneBox.setTitle(QtGui.QApplication.translate("MainWindow", "Osc. Detune", None, QtGui.QApplication.UnicodeUTF8))
        self.oscAWaveBox.setTitle(QtGui.QApplication.translate("MainWindow", "Osc. A Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.oscAPWMOn.setText(QtGui.QApplication.translate("MainWindow", "PWM", None, QtGui.QApplication.UnicodeUTF8))
        self.oscASawOn.setText(QtGui.QApplication.translate("MainWindow", "Saw", None, QtGui.QApplication.UnicodeUTF8))
        self.oscANoiseBox.setTitle(QtGui.QApplication.translate("MainWindow", "Osc. A Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.oscANoiseOn.setText(QtGui.QApplication.translate("MainWindow", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.oscANoiseOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.oscBEnableBox.setTitle(QtGui.QApplication.translate("MainWindow", "Osc. B Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.oscBOn.setText(QtGui.QApplication.translate("MainWindow", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.oscBOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.oscBWaveBox.setTitle(QtGui.QApplication.translate("MainWindow", "Osc. B Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.oscBWaveSquare.setText(QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.oscBWaveTri.setText(QtGui.QApplication.translate("MainWindow", "Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.oscBOctaveBox.setTitle(QtGui.QApplication.translate("MainWindow", "Osc. B Octave", None, QtGui.QApplication.UnicodeUTF8))
        self.oscBOctaveOn.setText(QtGui.QApplication.translate("MainWindow", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.oscBOctaveOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.oscFMBox.setTitle(QtGui.QApplication.translate("MainWindow", "Osc. FM", None, QtGui.QApplication.UnicodeUTF8))
        self.oscFMOn.setText(QtGui.QApplication.translate("MainWindow", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.oscFMOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Filter</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.filterAttackBox.setTitle(QtGui.QApplication.translate("MainWindow", "Attack", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDecayBox.setTitle(QtGui.QApplication.translate("MainWindow", "Decay", None, QtGui.QApplication.UnicodeUTF8))
        self.filterModeBox.setTitle(QtGui.QApplication.translate("MainWindow", "Filter Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.hpOn.setText(QtGui.QApplication.translate("MainWindow", "HP", None, QtGui.QApplication.UnicodeUTF8))
        self.lpOn.setText(QtGui.QApplication.translate("MainWindow", "LP", None, QtGui.QApplication.UnicodeUTF8))
        self.cutoffBox.setTitle(QtGui.QApplication.translate("MainWindow", "Cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.resonanceBox.setTitle(QtGui.QApplication.translate("MainWindow", "Resonance", None, QtGui.QApplication.UnicodeUTF8))
        self.envAmountBox.setTitle(QtGui.QApplication.translate("MainWindow", "Env. Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Amp</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ampAttackBox.setTitle(QtGui.QApplication.translate("MainWindow", "Attack", None, QtGui.QApplication.UnicodeUTF8))
        self.ampDecayBox.setTitle(QtGui.QApplication.translate("MainWindow", "Decay", None, QtGui.QApplication.UnicodeUTF8))
        self.envSustainBox.setTitle(QtGui.QApplication.translate("MainWindow", "Env. Sustain", None, QtGui.QApplication.UnicodeUTF8))
        self.envSustainOn.setText(QtGui.QApplication.translate("MainWindow", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.envSustainOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.glideBox.setTitle(QtGui.QApplication.translate("MainWindow", "Glide", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">LFO</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LFORateBox.setTitle(QtGui.QApplication.translate("MainWindow", "LFO Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.LFODepthBox.setTitle(QtGui.QApplication.translate("MainWindow", "LFO Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoEnableBox.setTitle(QtGui.QApplication.translate("MainWindow", "LFO Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoOn.setText(QtGui.QApplication.translate("MainWindow", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoDestBox.setTitle(QtGui.QApplication.translate("MainWindow", "LFO Dest.", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoOscOn.setText(QtGui.QApplication.translate("MainWindow", "Osc.", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoFilterOn.setText(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoWaveBox.setTitle(QtGui.QApplication.translate("MainWindow", "LFO Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoSquareOn.setText(QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoTriangleOn.setText(QtGui.QApplication.translate("MainWindow", "Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoRandomBox.setTitle(QtGui.QApplication.translate("MainWindow", "LFO Random", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoRandomOn.setText(QtGui.QApplication.translate("MainWindow", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.lfoRandomOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Effects</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pwmSweepBox.setTitle(QtGui.QApplication.translate("MainWindow", "PWM Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.pwmSweepOn.setText(QtGui.QApplication.translate("MainWindow", "PWM", None, QtGui.QApplication.UnicodeUTF8))
        self.pwmSweepOff.setText(QtGui.QApplication.translate("MainWindow", "Pulse", None, QtGui.QApplication.UnicodeUTF8))
        self.distortionBox.setTitle(QtGui.QApplication.translate("MainWindow", "Distortion", None, QtGui.QApplication.UnicodeUTF8))
        self.distortionOn.setText(QtGui.QApplication.translate("MainWindow", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.distortionOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasBox.setTitle(QtGui.QApplication.translate("MainWindow", "Anti-Alias", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasOn.setText(QtGui.QApplication.translate("MainWindow", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.antiAliasOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "&Options", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setShortcut(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setShortcut(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_as.setText(QtGui.QApplication.translate("MainWindow", "Save &as", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_as.setShortcut(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.action_MIDI_Channel.setText(QtGui.QApplication.translate("MainWindow", "&MIDI Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.action_MIDI_Channel.setShortcut(QtGui.QApplication.translate("MainWindow", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Export_patch_as_MIDI.setText(QtGui.QApplication.translate("MainWindow", "&Export patch as MIDI", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Export_patch_as_MIDI.setShortcut(QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Import_MIDI_patch.setText(QtGui.QApplication.translate("MainWindow", "&Import MIDI patch", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Import_MIDI_patch.setShortcut(QtGui.QApplication.translate("MainWindow", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setShortcut(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setShortcut(QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))

